version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      # Update wasmtime family crates together
      wasmtime:
        applies-to: version-updates
        patterns:
          - "^wasmtime(-.+)?$"
