package local:virt;

// in future this should be defined as a union world of the various
// virtual subsystems, when union syntax lands
world virtual-adapter {
  import wasi:cli/environment@0.2.1;
  import wasi:filesystem/preopens@0.2.1;
  import wasi:filesystem/types@0.2.1;
  import wasi:io/error@0.2.1;
  export wasi:io/error@0.2.1;
  import wasi:io/streams@0.2.1;
  export wasi:io/streams@0.2.1;
  import wasi:io/poll@0.2.1;
  export wasi:io/poll@0.2.1;
  export wasi:cli/environment@0.2.1;
  export wasi:filesystem/types@0.2.1;
  export wasi:filesystem/preopens@0.2.1;
  import wasi:cli/stdin@0.2.1;
  import wasi:cli/stdout@0.2.1;
  import wasi:cli/stderr@0.2.1;
  import wasi:cli/terminal-input@0.2.1;
  import wasi:cli/terminal-output@0.2.1;
  import wasi:cli/terminal-stdin@0.2.1;
  import wasi:cli/terminal-stdout@0.2.1;
  import wasi:cli/terminal-stderr@0.2.1;
  export wasi:cli/stdin@0.2.1;
  export wasi:cli/stdout@0.2.1;
  export wasi:cli/stderr@0.2.1;
  export wasi:cli/terminal-input@0.2.1;
  export wasi:cli/terminal-output@0.2.1;
  export wasi:cli/terminal-stdin@0.2.1;
  export wasi:cli/terminal-stdout@0.2.1;
  export wasi:cli/terminal-stderr@0.2.1;
  import wasi:clocks/monotonic-clock@0.2.1;
  export wasi:clocks/monotonic-clock@0.2.1;
  import wasi:http/types@0.2.1;
  export wasi:http/types@0.2.1;
  import wasi:http/outgoing-handler@0.2.1;
  export wasi:http/outgoing-handler@0.2.1;
  import wasi:sockets/ip-name-lookup@0.2.1;
  export wasi:sockets/ip-name-lookup@0.2.1;
  import wasi:sockets/tcp@0.2.1;
  export wasi:sockets/tcp@0.2.1;
  import wasi:sockets/udp@0.2.1;
  export wasi:sockets/udp@0.2.1;
  import wasi:config/store@0.2.0-draft;
  export wasi:config/store@0.2.0-draft;
}

world virtual-base {
}

world virtual-io {
  import wasi:io/error@0.2.1;
  export wasi:io/error@0.2.1;
  import wasi:io/streams@0.2.1;
  export wasi:io/streams@0.2.1;
  import wasi:io/poll@0.2.1;
  export wasi:io/poll@0.2.1;
}

// io components of subsystems
// where there is an intersection of
// streams + poll
world virtual-io-sockets {
  import wasi:sockets/ip-name-lookup@0.2.1;
  export wasi:sockets/ip-name-lookup@0.2.1;
  import wasi:sockets/tcp@0.2.1;
  export wasi:sockets/tcp@0.2.1;
  import wasi:sockets/udp@0.2.1;
  export wasi:sockets/udp@0.2.1;
}

world virtual-io-clocks {
  import wasi:clocks/monotonic-clock@0.2.1;
  export wasi:clocks/monotonic-clock@0.2.1;
}

world virtual-io-http {
  import wasi:http/types@0.2.1;
  export wasi:http/types@0.2.1;
  import wasi:http/outgoing-handler@0.2.1;
  export wasi:http/outgoing-handler@0.2.1;
}

world virtual-fs {
  import wasi:filesystem/preopens@0.2.1;
  import wasi:filesystem/types@0.2.1;
  export wasi:filesystem/types@0.2.1;
  export wasi:filesystem/preopens@0.2.1;
}

world virtual-stdio {
  import wasi:cli/stdin@0.2.1;
  import wasi:cli/stdout@0.2.1;
  import wasi:cli/stderr@0.2.1;
  import wasi:cli/terminal-input@0.2.1;
  import wasi:cli/terminal-output@0.2.1;
  import wasi:cli/terminal-stdin@0.2.1;
  import wasi:cli/terminal-stdout@0.2.1;
  import wasi:cli/terminal-stderr@0.2.1;
  export wasi:cli/stdin@0.2.1;
  export wasi:cli/stdout@0.2.1;
  export wasi:cli/stderr@0.2.1;
  export wasi:cli/terminal-input@0.2.1;
  export wasi:cli/terminal-output@0.2.1;
  export wasi:cli/terminal-stdin@0.2.1;
  export wasi:cli/terminal-stdout@0.2.1;
  export wasi:cli/terminal-stderr@0.2.1;
}

// remaining subsystems
world virtual-env {
  import wasi:cli/environment@0.2.1;
  export wasi:cli/environment@0.2.1;
}

world virtual-clocks {
  import wasi:clocks/monotonic-clock@0.2.1;
  export wasi:clocks/monotonic-clock@0.2.1;
  import wasi:clocks/wall-clock@0.2.1;
  export wasi:clocks/wall-clock@0.2.1;
}

world virtual-random {
  import wasi:random/insecure-seed@0.2.1;
  import wasi:random/insecure@0.2.1;
  import wasi:random/random@0.2.1;
  export wasi:random/insecure-seed@0.2.1;
  export wasi:random/insecure@0.2.1;
  export wasi:random/random@0.2.1;
}

world virtual-sockets {
  import wasi:sockets/ip-name-lookup@0.2.1;
  export wasi:sockets/ip-name-lookup@0.2.1;
  import wasi:sockets/tcp@0.2.1;
  export wasi:sockets/tcp@0.2.1;
  import wasi:sockets/udp@0.2.1;
  export wasi:sockets/udp@0.2.1;
  import wasi:sockets/instance-network@0.2.1;
  import wasi:sockets/tcp-create-socket@0.2.1;
  import wasi:sockets/udp-create-socket@0.2.1;
  export wasi:sockets/instance-network@0.2.1;
  export wasi:sockets/tcp-create-socket@0.2.1;
  export wasi:sockets/udp-create-socket@0.2.1;
  import wasi:sockets/network@0.2.1;
  export wasi:sockets/network@0.2.1;
}

world virtual-http {
  import wasi:http/types@0.2.1;
  export wasi:http/types@0.2.1;
  import wasi:http/incoming-handler@0.2.1;
  import wasi:http/outgoing-handler@0.2.1;
  export wasi:http/incoming-handler@0.2.1;
  export wasi:http/outgoing-handler@0.2.1;
}

world virtual-exit {
  import wasi:cli/exit@0.2.1;
  export wasi:cli/exit@0.2.1;
}

world virtual-config {
  import wasi:config/store@0.2.0-draft;
  export wasi:config/store@0.2.0-draft;
}

world virt-test {
  import wasi:clocks/wall-clock@0.2.1;
  import wasi:clocks/monotonic-clock@0.2.1;
  import wasi:filesystem/types@0.2.1;
  import wasi:sockets/instance-network@0.2.1;
  import wasi:sockets/ip-name-lookup@0.2.1;
  import wasi:sockets/network@0.2.1;
  import wasi:sockets/tcp-create-socket@0.2.1;
  import wasi:sockets/tcp@0.2.1;
  import wasi:sockets/udp-create-socket@0.2.1;
  import wasi:sockets/udp@0.2.1;
  import wasi:random/random@0.2.1;
  import wasi:random/insecure@0.2.1;
  import wasi:random/insecure-seed@0.2.1;
  import wasi:io/poll@0.2.1;
  import wasi:io/streams@0.2.1;
  import wasi:cli/environment@0.2.1;
  import wasi:config/store@0.2.0-draft;
  import wasi:filesystem/preopens@0.2.1;
  import wasi:cli/exit@0.2.1;
  import wasi:cli/stdin@0.2.1;
  import wasi:cli/stdout@0.2.1;
  import wasi:cli/stderr@0.2.1;
  import wasi:cli/terminal-input@0.2.1;
  import wasi:cli/terminal-output@0.2.1;
  import wasi:cli/terminal-stdin@0.2.1;
  import wasi:cli/terminal-stdout@0.2.1;
  import wasi:cli/terminal-stderr@0.2.1;

  export test-get-env: func() -> list<tuple<string, string>>;
  export test-get-config: func() -> list<tuple<string, string>>;
  export test-file-read: func(path: string) -> string;
  export test-stdio: func() -> ();
}
